<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" />
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Dropbox.Api" />
        <PackageReference Include="Irihi.Avalonia.Shared" />
        <PackageReference Include="Irihi.Ursa" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" />
        <PackageReference Include="ObservableCollections" />
        <PackageReference Include="Semi.Avalonia" />
        <PackageReference Include="Sortable.Avalonia" />
        <PackageReference Include="System.IO.Hashing" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\DateTimeDialog.axaml.cs">
        <DependentUpon>DateTimeDialog.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MonthDateSelect.axaml.cs">
        <DependentUpon>MonthDateSelect.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
